# Generated by Django
from django.db import migrations


def create_initial_tags(apps, schema_editor):
    Tag = apps.get_model("shortener", "Tag")
    tags = ["Marketing", "Social", "Personal", "Internal", "Educational"]
    for tag_name in tags:
        Tag.objects.get_or_create(name=tag_name)


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_tags),
    ]
